### ISSUE TITLE
What is "Profile" in the sample code in README

### ISSUE THREAD

**Issue by greenlaw110** [quickleft/react-loader#24]
The sample code references `Profile` in a couple places, can you please put the runnable source code into the repository to help to understand react-loader?

**Comment by mhuggins** [comment]
It's just an example react component.  Put whatever react component you want in its place, and that's the runnable example.q

**Comment by greenlaw110** [comment]
Actually I am quite interesting in the following code:

```javascript
    new Profile({ id: this.props.id }).fetch({
      success: this.onSuccess,
      error: this.onError
    })
```

Does reactjs provide `fetch` method to component?

**Comment by mhuggins** [comment]
Ahh, nope, that was intended to represent a backbone request.  I didn't realize that I called both the model and the component `Profile`, sorry about that.

**Comment by mhuggins** [comment]
It's simply intended to represent any kind of asynchronous fetch logic, that's all.  You could easily substitute it for a jQuery ajax request, a flux action & dispatch response, etc.
