### ISSUE TITLE
How can we show the spinner as an overlay?

### ISSUE THREAD

**Issue by agile116** [quickleft/react-loader#25]
Hi,
How can we show the spinner as an overlay? I want to see the page when loading.

**Comment by mhuggins** [comment]
Just make the spinner be a part of the page's content, with the children of the spinner representing the content that is not yet loaded.

**Comment by agile116** [comment]
But I can not see the existing data when the spinner is shown. For example, when a record add event is emitted, the spinner should be visible. But I want to see previously added items under the spinner. Any way to do that with react-loader?

杨小林

**Comment by mhuggins** [comment]
The loader is intended to be used in the context of whatever single item is loading.  So if you have a collection of many items that have already loaded, the loader should not encapsulate them.  Instead, only the new item should be wrapped in a loader.

**Comment by agile116** [comment]
Ok, got it. Thanks

杨小林
