### ISSUE TITLE
getDOMNode is deprecated in React 0.14.x

### ISSUE THREAD

**Issue by andersem** [quickleft/react-loader#29]
When using the loader in an 0.14-app, I get the following error:

```
Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by `Loader`.
```

This is because of this change in 0.14: https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#dom-node-refs

The new way to do it is:

```
var Zoo = React.createClass({
  render: function() {
    return <div>Giraffe name: <input ref="giraffe" /></div>;
  },
  showName: function() {
    // Previously: var input = this.refs.giraffe.getDOMNode();
    var input = this.refs.giraffe;
    alert(input.value);
  }
});
```

How should this be handled to maintain backwards compatibility in react-loader?

**Comment by dallonf** [comment]
Just fixed this in https://github.com/quickleft/react-loader/pull/26. You should just be able to update to react-loader@2.0.0

**Comment by andersem** [comment]
Oh, great! I should've searched better:-)

tir. 13. okt. 2015, 18.15 skrev Dallon Feldner <notifications@github.com>:
