### ISSUE TITLE
Accessing ref in Loader children

### ISSUE THREAD

**Issue by mischkew** [quickleft/react-loader#31]
Hey guys,

I try to access a ref in the children of Loader on componentDidMount. In this phase, the ref is always undefine, because react-loader does not render the children if loaded is false.

Example:
```coffee
componentDidMount: ->
  renderer = @refs['renderer'] # this is always undefined

render: ->
  return (
    <Loader loaded={@state.loaded}>
            <div id="editor">
                <RenderingCanvas ref="renderer" />
            </div>
    </Loader>
  )
```
How do you folks manage such requirements?

**Comment by mhuggins** [comment]
Yes, that is the intention of the loader.  It doesn't render what's inside the loader unless it's loaded.  Whenever you set the state of loaded, you should be able to get a reference to the chlid, e.g.:

```jsx
setState loaded: true, =>
  renderer = @refs['renderer']
```
