### ISSUE TITLE
Tests would crash when using react-loader - need to remove react/react-dom deps from react-loader

### ISSUE THREAD

**Issue by pypetey** [quickleft/react-loader#42]
Hi

I'm getting an error when I run tests in my application when react-loader is included in one of my components.

The main cause is that it loads react and react-dom additonally so with it my project loads reactjs 2 times and this causes an error. 

When I remove react/react-dom dependencies from node_modules in react-loader directory then it works flawlessly.

**Comment by mhuggins** [comment]
PR #41 should fix it.

**Comment by pypetey** [comment]
Awesome thanks for the info! :) I hope that it gets merged soon and released

**Comment by mhuggins** [comment]
Looks like it was just merged and released as 2.3.0

**Comment by mikekauffman** [comment]
Thanks for pointing this out, @pypetey, I have merged in #41 and published 2.3.0 to npm. Let me know if you are still having issues.
