### ISSUE TITLE
an onLoad event can be useful

### ISSUE THREAD

**Issue by keul** [quickleft/react-loader#45]
A nice new feature suggestion: why don't automatically handle an `onLoad` event property (an event handler function) that can be called when the spinner load it's contents?

This can help developers to take actions when loading is finished.

**Comment by mhuggins** [comment]
The spinner isn't responsible for doing the loading, so I'm not sure how that would work. The parent component should be responsible for managing state around whatever is being loaded.

Am I misunderstanding?

**Comment by keul** [comment]
You are right, this can be handled on the top level. My fault!
Thanks
