### ISSUE TITLE
Update for react 0.12

### ISSUE THREAD

**Issue by levitanong** [quickleft/react-loader#6]
Has some slight interference when used with projects requiring react 0.12. I just updated react-loader's package.json to use react 0.12 instead of 0.10, and it seems to work fine. In other words, all you guys need to do is update your package.json.

**Comment by mhuggins** [comment]
Thanks for the heads up!  I'll update ASAP.

**Comment by mhuggins** [comment]
@levitanong This is now address in [v1.1.0](https://www.npmjs.com/package/react-loader).  Please let me know if that addresses the issue for you so I can close this out, thanks!

**Comment by levitanong** [comment]
Works for me, thank you :)

**Comment by mhuggins** [comment]
Awesome, glad to hear it!
