### ISSUE TITLE
Cannot find module "spin" 

### ISSUE THREAD

**Issue by sam3k** [quickleft/react-loader#7]
I tried npm install and downloading directly the library but in both cases it throws an error saying the "spin" library does is not found.

**Comment by mhuggins** [comment]
It definitely exists (https://www.npmjs.com/package/spin)!  Could it have been an intermediate npm issue?

**Comment by sam3k** [comment]
RIght, but try to do a `npm install react-loader` on it. It does not attempt to install any node_modules it requires. (including spin)

Furthermore, since it is a client side dependency, you should bundle spin inside the lib folder for those who decide to just hit the download button.

**Comment by levitanong** [comment]
As a temporary workaround, you can change your cwd to react-loader, then `npm install` to install all of react-loader's dependencies including spin.

**Comment by mhuggins** [comment]
@sam3k The way npm works is that you need to [define a package.json file](https://docs.npmjs.com/files/package.json), then run `npm install` on your folder.  This will install your dependencies along with any sub-dependencies.

**Comment by nonsensery** [comment]
It looks like the version of this react-loader on `npm` is out of date. PR #4 fixed this issue.

**Comment by mhuggins** [comment]
@sam3k This is now address in [v1.1.0](https://www.npmjs.com/package/react-loader).  Please let me know if that addresses the issue for you so I can close this out, thanks!

**Comment by levitanong** [comment]
Works for me.
